<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MrB" failures="3" tests="7" name="TestNamme" time="2.728" errors="0" timestamp="2021-03-10T23:24:58 EST">
  <testcase classname="roughTrials.ExtentReporter" name="Testcase2" time="0.035">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[]name&amp;gt; but was:&amp;lt;[a]name&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[]name> but was:<[a]name>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at roughTrials.ExtentReporter.Testcase2(ExtentReporter.java:105)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Testcase2 -->
  <testcase classname="roughTrials.ExtentReporter" name="Testcase3" time="0.003">
    <skipped/>
  </testcase> <!-- Testcase3 -->
  <testcase classname="roughTrials.ExtentReporter" name="cas2" time="0.005">
    <skipped/>
  </testcase> <!-- cas2 -->
  <testcase classname="roughTrials.ExtentReporter" name="case1" time="0.004"/>
  <testcase classname="roughTrials.ExtentReporter" name="case3" time="0.003">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[]name&amp;gt; but was:&amp;lt;[my]name&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[]name> but was:<[my]name>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at roughTrials.ExtentReporter.case3(ExtentReporter.java:162)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- case3 -->
  <testcase classname="roughTrials.JDBCMysqlTest" name="mysqlDML" time="1.35">
    <failure type="java.sql.SQLIntegrityConstraintViolationException" message="Cannot add or update a child row: a foreign key constraint fails (`traffic_violations_db`.`officers`, CONSTRAINT `FK_Officers` FOREIGN KEY (`OfficerID`) REFERENCES `violations` (`OfficerID`))">
      <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`traffic_violations_db`.`officers`, CONSTRAINT `FK_Officers` FOREIGN KEY (`OfficerID`) REFERENCES `violations` (`OfficerID`))
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
at roughTrials.JDBCMysqlTest.mysqlDML(JDBCMysqlTest.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- mysqlDML -->
  <testcase classname="roughTrials.JDBCMysqlTest" name="mysqlSelect" time="0.125"/>
  <testcase classname="roughTrials.ExtentReporter" name="mysqlSelect" time="0.0">
    <ignored/>
  </testcase> <!-- mysqlSelect -->
  <testcase classname="roughTrials.ExtentReporter" name="Testcase1" time="0.0">
    <ignored/>
  </testcase> <!-- Testcase1 -->
</testsuite> <!-- TestNamme -->
